modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="pinchat"
version="${file.jarVersion}"
displayName="Pinchat Mod"
description='''Pinchat Mod'''

[[dependencies.pinchat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pinchat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
