license="MIT"
[[mods]]
modId="pinchat"
version="${mod_version}"
displayName="PinChat"
description='''Pin chat messages and organize them into movable groups.'''

[[mixins]]
config="pinchat.mixins.json"

[[dependencies.pinchat]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_dependency}"
    ordering="NONE"
    side="BOTH"

[[dependencies.pinchat]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.0.19-beta,)"
    ordering="NONE"
    side="BOTH"
